using better word in persian
iran-react-community/docs pull request #10
Opened 2019-06-01 08:01 UTC by mehrdad88sh

Fix #9

2019-06-01 13:37 UTC, amerllica requested changes

2019-06-01 13:37 UTC, amerllica commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
<p dir=rtl>
لطفا این فایل و کلا فولدر idea را از پروژه حذف کنید و در gitignore قرار دهید
</p>

2019-06-06 19:44 UTC, niiima approved these changes
It get review and get approved as 'طرح' it's an better alternative for 'پرسش' base on body of the sentence.

2019-06-06 20:48 UTC, niiima requested changes
This PR is requesting direct merge into master branch that is not a good practise and might courses merge conflicts.
I am asking for feature pull requests to get ask for dev branch instead of master 
and then merge back into master branch from there.

2019-06-06 20:50 UTC, niiima commented
Please use dev branch as a merge target and resend your PR.

2019-06-06 20:50 UTC, closed without merging